### CREATE
POST http://localhost:8081/item
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "12345"
}

> {%
    if(response.body["id"]) {
        client.global.set("id", response.body.id);
    }
%}

### GET
GET http://localhost:8081/item/{{id}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET ALL
GET http://localhost:8081/items
Accept: application/json
Authorization: Bearer {{accessToken}}

### UPDATE
PUT http://localhost:8081/item/{{id}}
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "updated"
}

### DELETE
DELETE http://localhost:8081/item/{{id}}
Accept: application/json
Authorization: Bearer {{accessToken}}
