### CREATE
POST http://localhost:8081/item
Content-Type: application/json

{
  "name": "test"
}

> {%
    if(response.body["id"]) {
        client.global.set("id", response.body.id);
    }
%}

### GET
GET http://localhost:8081/item/{{id}}
Accept: application/json

### GET ALL
GET http://localhost:8081/items
Accept: application/json

### UPDATE
PUT http://localhost:8081/item/{{id}}
Accept: application/json

{
  "name": "updated"
}

### DELETE
DELETE http://localhost:8081/item/{{id}}
Accept: application/json
